/* Generated by scripts/gen_contracts.py from server/contracts.py. Do not edit. */

/**
 * What the trainee can call a track (Classify step).
 *
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Label".
 */
export type Label = "bird" | "friendly" | "civil" | "recon" | "fpv" | "loitering" | "decoy" | "unknown";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "ControlLink".
 */
export type ControlLink = "rf" | "fiber" | "none";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Nav".
 */
export type Nav = "gnss" | "gnss_ins" | "manual" | "none";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "EffectKind".
 */
export type EffectKind = "rf_jam" | "gnss_spoof" | "laser" | "rocket" | "missile" | "sam" | "gun";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SensorType".
 */
export type SensorType = "radar" | "rf" | "acoustic" | "eoir" | "iff";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "TimeOfDay".
 */
export type TimeOfDay = "day" | "dusk" | "night";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Weather".
 */
export type Weather = "clear" | "haze" | "rain" | "fog";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "RoeState".
 */
export type RoeState = "weapons_free" | "weapons_tight" | "weapons_hold";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Tactic".
 */
export type Tactic =
  "direct" | "split_flank" | "decoy_first" | "time_on_target" | "terrain_masked" | "recon_then_strike";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "DroneClass".
 */
export type DroneClass =
  "bird" | "friendly_uav" | "civil_drone" | "recon_quad" | "fpv_rf" | "fpv_fiber" | "loitering_munition" | "decoy";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Skill".
 */
export type Skill = "S1" | "S2" | "S3" | "S4" | "S5" | "S6" | "S7" | "S8";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "session_start"
  | "session_end"
  | "track_new"
  | "track_lost"
  | "track_regained"
  | "hook"
  | "classify"
  | "ai_suggestion"
  | "decision"
  | "authority_request"
  | "authority_granted"
  | "engage_order"
  | "engage_blocked"
  | "engage_result"
  | "cease"
  | "neutralised"
  | "link_lost"
  | "diverted"
  | "leaker"
  | "exited"
  | "expended"
  | "recon_complete"
  | "collateral"
  | "friendly_affected"
  | "sensor_state"
  | "camera"
  | "camera_designate"
  | "pause"
  | "resume";
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Outcome".
 */
export type Outcome = "active" | "neutralised" | "link_lost" | "diverted" | "leaked" | "exited" | "expended";

export interface Contracts {
  Catalogue?: Catalogue;
  Scenario?: Scenario;
  SessionResult?: SessionResult;
  SimEvent?: SimEvent;
  TruthEntity?: TruthEntity;
  Replay?: Replay;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Catalogue".
 */
export interface Catalogue {
  drones: {
    [k: string]: DroneSpec;
  };
  effectors: {
    [k: string]: EffectorSpec;
  };
  sensors: {
    [k: string]: SensorSpec;
  };
  effect_matrix: {
    [k: string]: {
      [k: string]: number;
    };
  };
  laser_dwell: {
    [k: string]: number;
  };
  weather: {
    [k: string]: WeatherEffect;
  };
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "DroneSpec".
 */
export interface DroneSpec {
  name: string;
  label: Label;
  hostile: boolean;
  size_m: number;
  cruise_mps: number;
  terminal_mps: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  alt_m: [number, number];
  rcs_m2: number;
  /**
   * IR brightness 0..1
   */
  thermal: number;
  acoustic_db: number;
  link: ControlLink;
  nav: Nav;
  rf_band: string | null;
  iff: boolean;
  cost_inr: number;
  damage: number;
  source: string | null;
  illustrative: boolean;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "EffectorSpec".
 */
export interface EffectorSpec {
  name: string;
  kind: EffectKind;
  kill: "soft" | "hard";
  range_m: number;
  /**
   * per activation (soft kill) or per round (hard kill)
   */
  cost_inr: number;
  ammo: number | null;
  rounds_per_shot: number;
  sector_half_deg: number;
  duration_s: number;
  exposure_s: number;
  dwell_s: number;
  slew_s: number;
  speed_mps: number;
  blast_m: number;
  pk: number;
  cycle_s: number;
  needs_los: boolean;
  source: string | null;
  illustrative: boolean;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SensorSpec".
 */
export interface SensorSpec {
  name: string;
  type: SensorType;
  range_m: number;
  update_s: number;
  params: {
    [k: string]: number;
  };
  source: string | null;
  illustrative: boolean;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "WeatherEffect".
 */
export interface WeatherEffect {
  radar: number;
  laser_dwell: number;
  laser_ok: boolean;
  ambient_db: number;
  eo_vis_km: number;
  ir_vis_km: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Scenario".
 */
export interface Scenario {
  id: string;
  name: string;
  seed: number;
  mode: "scripted" | "procedural" | "benchmark" | "drill";
  briefing: string;
  intel: string;
  duration_s: number;
  map: MapSpec;
  environment: Environment;
  roe: Roe;
  sensors: SensorPlacement[];
  effectors: EffectorPlacement[];
  waves: Wave[];
  clutter: Clutter;
  difficulty: Difficulty;
  tags: string[];
  fingerprint: string;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "MapSpec".
 */
export interface MapSpec {
  terrain_seed: number;
  terrain: "plains" | "foothills";
  size_m: number;
  assets: Asset[];
  no_fire_zones: NoFireZone[];
  corridors: Corridor[];
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Asset".
 */
export interface Asset {
  id: string;
  name: string;
  type: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pos: [number, number];
  value: number;
  radius_m: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "NoFireZone".
 */
export interface NoFireZone {
  id: string;
  name: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  center: [number, number];
  radius_m: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Corridor".
 */
export interface Corridor {
  id: string;
  name: string;
  points: [number, number][];
  alt_m: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Environment".
 */
export interface Environment {
  time_of_day: TimeOfDay;
  weather: Weather;
  ambient_noise_db: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Roe".
 */
export interface Roe {
  state: RoeState;
  authority_delay_s: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SensorPlacement".
 */
export interface SensorPlacement {
  id: string;
  type: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pos: [number, number];
  events: SensorEvent[];
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SensorEvent".
 */
export interface SensorEvent {
  t: number;
  state: "down" | "degraded";
  for_s: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "EffectorPlacement".
 */
export interface EffectorPlacement {
  id: string;
  type: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pos: [number, number];
  ammo: number | null;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Wave".
 */
export interface Wave {
  id: string;
  t: number;
  tactic: Tactic;
  bearing_deg: number;
  spread_deg: number;
  range_m: number;
  target: string;
  units: WaveUnit[];
  arrival_s: number | null;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "WaveUnit".
 */
export interface WaveUnit {
  cls: DroneClass;
  n: number;
}
export interface Clutter {
  bird_flocks: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  birds_per_flock: [number, number];
  friendly_flights: FriendlyFlight[];
  civil_drones: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "FriendlyFlight".
 */
export interface FriendlyFlight {
  id: string;
  corridor: string;
  t: number;
  iff: boolean;
}
export interface Difficulty {
  level: number;
  focus: Skill[];
  load: {
    [k: string]: number;
  };
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SessionResult".
 */
export interface SessionResult {
  scenario_id: string;
  seed: number;
  actor: "trainee" | "bot";
  bot: string | null;
  duration_s: number;
  ended_reason: "all_resolved" | "time_up" | "aborted";
  assets_health: {
    [k: string]: number;
  };
  aid_mode: "off" | "honest" | "unreliable";
  events: SimEvent[];
  truth: TruthEntity[];
  replay: Replay | null;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "SimEvent".
 */
export interface SimEvent {
  t: number;
  type: EventType;
  actor: "trainee" | "sim" | "bot";
  track: string | null;
  entity: string | null;
  data: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "TruthEntity".
 */
export interface TruthEntity {
  id: string;
  cls: DroneClass;
  label: Label;
  hostile: boolean;
  link: ControlLink;
  nav: Nav;
  cost_inr: number;
  damage: number;
  wave: string | null;
  tactic: Tactic | null;
  iff: boolean;
  track: string | null;
  t_spawn: number;
  t_first_displayed: number | null;
  outcome: Outcome;
  outcome_t: number | null;
  outcome_by: string | null;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Replay".
 */
export interface Replay {
  dt: number;
  entities: ReplayEntity[];
  tracks: string[];
  effectors: string[];
  frames: ReplayFrame[];
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "ReplayEntity".
 */
export interface ReplayEntity {
  id: string;
  cls: DroneClass;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "ReplayFrame".
 */
export interface ReplayFrame {
  t: number;
  /**
   * per entity: index, x, y, z, state(0 active,1 down)
   */
  e: number[];
  /**
   * per track: index, x, y, displayed, label idx, decision idx, hooked
   */
  tr: number[];
  /**
   * az_deg, el_deg, fov_deg, mode(0 eo,1 ir)
   */
  cam: number[];
  /**
   * per active effector: effector idx, track idx
   */
  fx: number[];
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Clutter".
 */
export interface Clutter1 {
  bird_flocks: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  birds_per_flock: [number, number];
  friendly_flights: FriendlyFlight[];
  civil_drones: number;
}
/**
 * This interface was referenced by `Contracts`'s JSON-Schema
 * via the `definition` "Difficulty".
 */
export interface Difficulty1 {
  level: number;
  focus: Skill[];
  load: {
    [k: string]: number;
  };
}
