"""Export server/contracts.py to JSON Schema, generate sim/src/contracts.ts, and
write the normalised catalogue (schemas/catalogue.json) the TS side loads.

Usage:  .venv/bin/python scripts/gen_contracts.py [--check]

--check exits non-zero if the committed files differ from what would be
generated (used by tests/test_contracts.py).
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from server.content import catalogue_json  # noqa: E402
from server.contracts import EXPORTED  # noqa: E402

SCHEMA_PATH = ROOT / "schemas" / "contracts.schema.json"
TS_PATH = ROOT / "sim" / "src" / "contracts.ts"
CATALOGUE_PATH = ROOT / "schemas" / "catalogue.json"


def _draft7_tuples(node):
    """pydantic emits 2020-12 `prefixItems`; json-schema-to-typescript wants draft-07 `items: [...]`."""
    if isinstance(node, dict):
        if "prefixItems" in node:
            node["items"] = node.pop("prefixItems")
            node["additionalItems"] = False
        for v in node.values():
            _draft7_tuples(v)
    elif isinstance(node, list):
        for v in node:
            _draft7_tuples(v)
    return node


def _strip_property_titles(node, is_properties=False):
    """Drop per-field titles so json2ts inlines primitives instead of minting Name1, Name2, ..."""
    if isinstance(node, dict):
        if is_properties:
            for v in node.values():
                if isinstance(v, dict):
                    v.pop("title", None)
        for k, v in node.items():
            _strip_property_titles(v, is_properties=(k == "properties"))
    elif isinstance(node, list):
        for v in node:
            _strip_property_titles(v)
    return node


def build_schema() -> dict:
    defs: dict = {}
    props: dict = {}
    for model in EXPORTED:
        s = model.model_json_schema(ref_template="#/$defs/{model}", mode="serialization")
        defs.update(s.pop("$defs", {}))
        defs[model.__name__] = s
        props[model.__name__] = {"$ref": f"#/$defs/{model.__name__}"}
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Contracts",
        "type": "object",
        "properties": props,
        "additionalProperties": False,
        "$defs": dict(sorted(defs.items())),
    }
    return _strip_property_titles(_draft7_tuples(schema))


def generate_ts(schema_path: Path) -> str:
    out = subprocess.run(
        ["npx", "--no-install", "json2ts", "-i", str(schema_path), "--unreachableDefinitions",
         "--additionalProperties", "false", "--bannerComment",
         "/* Generated by scripts/gen_contracts.py from server/contracts.py. Do not edit. */"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    )
    return out.stdout


def main() -> int:
    check = "--check" in sys.argv
    schema_text = json.dumps(build_schema(), indent=2) + "\n"
    cat_text = json.dumps(catalogue_json(), indent=1) + "\n"
    if check:
        if not CATALOGUE_PATH.exists() or CATALOGUE_PATH.read_text() != cat_text:
            print("schemas/catalogue.json is stale; run scripts/gen_contracts.py")
            return 1
        if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text() != schema_text:
            print("schemas/contracts.schema.json is stale; run scripts/gen_contracts.py")
            return 1
        ts = generate_ts(SCHEMA_PATH)
        if not TS_PATH.exists() or TS_PATH.read_text() != ts:
            print("sim/src/contracts.ts is stale; run scripts/gen_contracts.py")
            return 1
        print("contracts up to date")
        return 0
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(schema_text)
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text(generate_ts(SCHEMA_PATH))
    CATALOGUE_PATH.write_text(cat_text)
    print(f"wrote {SCHEMA_PATH.relative_to(ROOT)}, {TS_PATH.relative_to(ROOT)} and {CATALOGUE_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
